# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28dcf7155610dac623eb2508aef74c550aee80583b04ad00f8a15178bdc21793d51552ee03bbcd455f7cbfcfa1a41e20af020d38536cda9ee5507a7f624b25c7

test:
  secret_key_base: a851ddc401b72f0b17a9515947b447fd557a4cac6786a691b5ba31b62bebb93fe44355bc43f6b61428e242e29d4addb2706faa3ca107ec0d39b105247215b0ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
